from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Any

from .models import ApprovedAnswer, ApplicationForm, FieldKind, ResolvedAnswers


# These values may never be inferred from a resume or generated by an LLM.  They are
# only usable when the user saved an explicit answer.  They still block unattended
# submission unless that exact saved answer is separately approved for submission.
SENSITIVE_KEYS = frozenset(
    {
        "work_authorization",
        "requires_sponsorship",
        "citizenship",
        "security_clearance",
        "salary_expectation",
        "relocation",
        "gender",
        "race_ethnicity",
        "veteran_status",
        "disability_status",
        "criminal_history",
        "legal_attestation",
        "signature",
        "terms_consent",
    }
)

# Free-form generated prose must be reviewed in the first version of the runner.
REVIEW_ONLY_KEYS = frozenset({"cover_letter", "why_company", "freeform_question"})

_ALIASES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("first_name", ("first name", "given name", "firstname")),
    ("last_name", ("last name", "family name", "surname", "lastname")),
    ("preferred_name", ("preferred name", "chosen name")),
    ("full_name", ("full name", "legal name")),
    ("email", ("email address", "email")),
    ("phone", ("phone number", "mobile phone", "telephone", "phone")),
    ("address_line_2", ("address line 2", "apartment", "apt/suite", "suite")),
    ("address_line_1", ("street address", "address line 1", "address")),
    ("city", ("city",)),
    ("state", ("state/province", "state or province", "province", "state")),
    ("postal_code", ("zip code", "postal code", "zip")),
    ("country", ("country",)),
    ("linkedin_url", ("linkedin profile", "linkedin url", "linkedin")),
    ("github_url", ("github profile", "github url", "github")),
    ("portfolio_url", ("portfolio url", "personal website", "website")),
    ("school", ("university", "college", "school")),
    ("degree", ("degree",)),
    ("major", ("field of study", "fields of study", "major", "discipline", "disciplines")),
    ("graduation_month", ("graduation month",)),
    ("graduation_year", ("graduation year",)),
    ("graduation_date", ("graduation date", "expected graduation")),
    ("resume", ("resume/cv", "resume", "cv")),
    ("cover_letter", ("cover letter",)),
    ("requires_sponsorship", ("require sponsorship", "need sponsorship", "visa sponsorship", "sponsorship")),
    ("work_authorization", ("authorized to work", "work authorization", "legally authorized")),
    ("citizenship", ("citizenship", "citizen status")),
    ("security_clearance", ("security clearance", "clearance")),
    ("salary_expectation", ("salary expectation", "desired salary", "compensation expectation")),
    ("relocation", ("willing to relocate", "relocation")),
    ("veteran_status", ("veteran status", "protected veteran", "veteran")),
    ("disability_status", ("disability status", "self-identify disability", "disability")),
    ("race_ethnicity", ("race/ethnicity", "race and ethnicity", "ethnicity", "race")),
    ("gender", ("gender identity", "gender")),
    ("pronouns", ("pronouns",)),
    ("criminal_history", ("criminal history", "convicted", "criminal record")),
    ("legal_attestation", ("attest", "certify", "truthful", "accurate information")),
    ("signature", ("electronic signature", "signature")),
    ("terms_consent", ("privacy policy", "terms and conditions", "consent")),
    ("why_company", ("why do you want", "why this company", "why us")),
)


def normalize_question(value: str) -> str:
    value = re.sub(r"\s+", " ", value.strip().lower())
    return re.sub(r"[^a-z0-9 +/#_-]", "", value)


def canonical_key(label: str, name: str = "", input_type: str = "") -> str:
    haystack = normalize_question(f"{label} {name}")
    if input_type == "file":
        return "resume" if "cover" not in haystack else "cover_letter"
    alias_haystack = re.sub(r"[_-]+", " ", haystack)
    priority_keys = SENSITIVE_KEYS | REVIEW_ONLY_KEYS
    ordered_aliases = (
        tuple(item for item in _ALIASES if item[0] in priority_keys)
        + tuple(item for item in _ALIASES if item[0] not in priority_keys)
    )
    for key, aliases in ordered_aliases:
        if any(
            re.search(
                rf"(?<![a-z0-9]){re.escape(re.sub(r'[_-]+', ' ', alias))}(?![a-z0-9])",
                alias_haystack,
            )
            for alias in aliases
        ):
            return key
    safe_name = re.sub(r"[^a-z0-9]+", "_", normalize_question(name or label)).strip("_")
    return safe_name or "unknown_field"


class AnswerPolicy:
    """Resolve inspected questions using only explicit, user-approved data."""

    def __init__(self, require_review_on_unknown_question: bool = True):
        self.require_review_on_unknown_question = require_review_on_unknown_question

    def resolve(
        self,
        form: ApplicationForm,
        profile: Mapping[str, Any],
        saved_answers: Sequence[ApprovedAnswer],
        *,
        resume_path: str | None = None,
    ) -> ResolvedAnswers:
        answer_by_key = {answer.key: answer for answer in saved_answers}
        values: dict[str, Any] = {}
        blockers: list[str] = []
        unknown_required: list[str] = []
        review_keys: list[str] = []

        for field in form.fields:
            key = field.key
            saved = answer_by_key.get(key)
            is_sensitive = field.sensitive or key in SENSITIVE_KEYS or bool(
                saved and saved.sensitive
            )
            if saved:
                saved_pattern = normalize_question(saved.question_pattern or "")
                current_pattern = normalize_question(field.label)
                if saved_pattern and saved_pattern != current_pattern:
                    saved = None
                elif is_sensitive and not saved_pattern:
                    # Sensitive answers are never reusable by key alone: labels such
                    # as work authorization can refer to different countries or terms.
                    saved = None
            value: Any = None
            approved_for_submission = False

            if field.kind is FieldKind.FILE and key == "resume" and resume_path:
                value = resume_path
                approved_for_submission = True
            elif field.kind is FieldKind.FILE:
                # No database value may name an arbitrary local file. Only the
                # operator-configured resume path is eligible for upload.
                value = None
            elif saved and saved.approved_for_autofill:
                value = saved.value
                approved_for_submission = saved.approved_for_submission
            elif key not in SENSITIVE_KEYS and key not in REVIEW_ONLY_KEYS:
                value = profile.get(key)
                if key == "full_name" and value is None:
                    value = " ".join(
                        part for part in (profile.get("first_name"), profile.get("last_name")) if part
                    ) or None
                elif key == "graduation_date" and value is None:
                    year = profile.get("graduation_year")
                    month = profile.get("graduation_month")
                    if year and month:
                        value = f"{year}-{str(month).zfill(2)}"
                # Structured identity/profile fields are safe to use when the user
                # explicitly placed them in application_profile.
                approved_for_submission = value is not None

            has_value = value is not None and value != ""
            if has_value:
                values[key] = value

            if field.required and not has_value:
                unknown_required.append(key)

            if is_sensitive and has_value and not approved_for_submission:
                review_keys.append(key)
                blockers.append(f"{key}: explicit submission approval required")
            elif key in REVIEW_ONLY_KEYS and has_value:
                review_keys.append(key)
                blockers.append(f"{key}: free-form answer requires review")
            elif saved and has_value and not saved.approved_for_submission:
                review_keys.append(key)
                blockers.append(f"{key}: answer is approved for autofill only")

        if self.require_review_on_unknown_question:
            for key in unknown_required:
                blockers.append(f"{key}: required answer is missing")

        return ResolvedAnswers(
            values=values,
            blockers=tuple(dict.fromkeys(blockers)),
            unknown_required=tuple(dict.fromkeys(unknown_required)),
            review_keys=tuple(dict.fromkeys(review_keys)),
        )
